---
# This automation simulates the use of the IKEA TRADFRI Dimmer control
# connected through ZHA.

blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_1button_remote_custom.yaml

  name: ZHA - IKEA TRADFRI - 1 Button Remote - Custom Actions

  description: >-
    This automation simulates the use of the IKEA TRADFRI SHORTCUT Button
    connected through ZHA.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: TRADFRI SHORTCUT Button
    short:
      name: Short Press
      description: The action to perform on Short Press
      selector:
        action:
      default: []
    long:
      name: Long Press
      description: The action to perform on Long Press
      selector:
        action:
      default: []
    double:
      name: Double Press
      description: The action to perform on Double Press
      selector:
        action:
      default: []  

mode: single
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Short-Press
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "on" }}'
        sequence:
          - choose: []
            default: !input short
          - delay:
              milliseconds: 500

      # Long-Press
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - choose: []
            default: !input long
          - delay:
              milliseconds: 500
      # Double-Press
      - conditions:
          - condition: template
            value_template: 'todo'
        sequence:
          - choose: []
            default: !input double
          - delay:
              milliseconds: 500  
    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []
